version: '3.8'

services:
  web:
    image: node:20-alpine
    container_name: image-gallery-dev
    working_dir: /app
    # This command installs dependencies if node_modules is missing, then starts the dev server.
    command: >
      sh -c "if [ ! -d 'node_modules' ]; then npm install; fi && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      # Mount the entire project directory for hot-reloading
      - .:/app
      # Use a named volume for node_modules to avoid overwriting it from the host
      - node_modules:/app/node_modules
    # Load environment variables from a .env file in the project root
    env_file:
      - .env

volumes:
  node_modules: